layout_spectrum: 0.5340502
typography_spectrum: 0.5250896
color:
  saturation: 0.3606286
  lightness: 0.9414427
  brandStrength: 0.9853542
  rhythmicContrast: 0.5649635
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: ashleyneale
